# Generated by Django 2.0 on 2020-01-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=32)),
                ('b_price', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
