# Generated by Django 2.2.7 on 2020-01-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=128)),
                ('s_age', models.IntegerField(max_length=10)),
                ('s_sex', models.BooleanField(default=True)),
            ],
        ),
    ]
