# Generated by Django 2.2.7 on 2020-01-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycache', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
